APPNAME = my_ws01.py

all:

run:
	flask run

info:
	@echo "Exporta las siguientes variables de entorno en tu terminal..."
	@echo "export FLASK_APP=${APPNAME}"
	@echo "export FLASK_ENV=development"

.PHONY: all